# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='opencv.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0copencv.proto\"\xa1\x01\n\rOpenCVRequest\x12\x13\n\x0b\x62usiness_id\x18\x01 \x01(\t\x12\x16\n\x0einterface_mode\x18\x02 \x01(\x05\x12\x14\n\x0cimage_buffer\x18\x03 \x01(\x0c\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\x14\n\x0crequest_type\x18\x06 \x01(\x05\x12\x12\n\ncontext_id\x18\x07 \x01(\x05\"\x9f\x01\n\x0eOpenCVResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.OpenCVResponse.Category\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x12\n\ncontext_id\x18\x03 \x01(\x05\x12\x12\n\nerror_code\x18\x04 \x01(\x05\x1a(\n\x08\x43\x61tegory\x12\x0c\n\x04\x66std\x18\x01 \x01(\x02\x12\x0e\n\x06\x66score\x18\x02 \x01(\x02\x32\x38\n\x06OpenCV\x12.\n\tRunOpenCV\x12\x0e.OpenCVRequest\x1a\x0f.OpenCVResponse\"\x00\x62\x06proto3'
)




_OPENCVREQUEST = _descriptor.Descriptor(
  name='OpenCVRequest',
  full_name='OpenCVRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='business_id', full_name='OpenCVRequest.business_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface_mode', full_name='OpenCVRequest.interface_mode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_buffer', full_name='OpenCVRequest.image_buffer', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_url', full_name='OpenCVRequest.image_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='OpenCVRequest.trace_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_type', full_name='OpenCVRequest.request_type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context_id', full_name='OpenCVRequest.context_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=178,
)


_OPENCVRESPONSE_CATEGORY = _descriptor.Descriptor(
  name='Category',
  full_name='OpenCVResponse.Category',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fstd', full_name='OpenCVResponse.Category.fstd', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fscore', full_name='OpenCVResponse.Category.fscore', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=340,
)

_OPENCVRESPONSE = _descriptor.Descriptor(
  name='OpenCVResponse',
  full_name='OpenCVResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='OpenCVResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='OpenCVResponse.trace_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context_id', full_name='OpenCVResponse.context_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='OpenCVResponse.error_code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_OPENCVRESPONSE_CATEGORY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=340,
)

_OPENCVRESPONSE_CATEGORY.containing_type = _OPENCVRESPONSE
_OPENCVRESPONSE.fields_by_name['results'].message_type = _OPENCVRESPONSE_CATEGORY
DESCRIPTOR.message_types_by_name['OpenCVRequest'] = _OPENCVREQUEST
DESCRIPTOR.message_types_by_name['OpenCVResponse'] = _OPENCVRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpenCVRequest = _reflection.GeneratedProtocolMessageType('OpenCVRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENCVREQUEST,
  '__module__' : 'opencv_pb2'
  # @@protoc_insertion_point(class_scope:OpenCVRequest)
  })
_sym_db.RegisterMessage(OpenCVRequest)

OpenCVResponse = _reflection.GeneratedProtocolMessageType('OpenCVResponse', (_message.Message,), {

  'Category' : _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
    'DESCRIPTOR' : _OPENCVRESPONSE_CATEGORY,
    '__module__' : 'opencv_pb2'
    # @@protoc_insertion_point(class_scope:OpenCVResponse.Category)
    })
  ,
  'DESCRIPTOR' : _OPENCVRESPONSE,
  '__module__' : 'opencv_pb2'
  # @@protoc_insertion_point(class_scope:OpenCVResponse)
  })
_sym_db.RegisterMessage(OpenCVResponse)
_sym_db.RegisterMessage(OpenCVResponse.Category)



_OPENCV = _descriptor.ServiceDescriptor(
  name='OpenCV',
  full_name='OpenCV',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=342,
  serialized_end=398,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunOpenCV',
    full_name='OpenCV.RunOpenCV',
    index=0,
    containing_service=None,
    input_type=_OPENCVREQUEST,
    output_type=_OPENCVRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPENCV)

DESCRIPTOR.services_by_name['OpenCV'] = _OPENCV

# @@protoc_insertion_point(module_scope)
